### PR TITLE
Beta.8

### PR DESCRIPTION
**Pull request by CDK2020**

### CODE REVIEW

**Comment by CDK2020** [comment]
We should try to get the js dist file size down, maybe remove emojione as a dependency

**Comment by datitisev** [comment]
@CDK2020 flarum/flarum-ext-emoji is going to be using twemoji for beta 8 (see https://github.com/flarum/flarum-ext-emoji/pull/16).
We probably want to switch to that once that PR is merged.

**Comment by CDK2020** [comment]
@datitisev the only problem is they don't seem to have a helper to render the emoji. We would have to include our own version or twemoji unless there is a way to use the npm dependency already included in emoji.

**Comment by datitisev** [comment]
@CDK2020 Sadly, there is not. That would require the emoji extension to always be enabled, which tbh most forums probably use it, but we shouldn't depend on it.

We may want to use unicode emojis than EmojiOne emojis, like the emoji extension is going to.
The twemoji library would just be for the emoji list. From emoji name -> unicode code.

**Comment by CDK2020** [comment]
@datitisev so we would let the client choose how to render it? We would still need someway to convert the name to the Unicode since we do that in the admin panel. I would vote we do it the old way and use emoji one, but write our own lil library for getting the emoji image.

We could also force people to get the license for it, it's free.

**Comment by datitisev** [comment]
@CDK2020 Hm, I thought the twemoji library had the name tree, but it doesn't seem like it does.
We can use emojibase-data as described [in its wiki](https://milesj.gitbook.io/emojibase/data#compact-format) to use an emoji map & get the corresponding hexcode.

We may also want to consider saving the shortcodes to the database instead of the shortname to avoid having to convert them every time they are shown.

**Comment by CDK2020** [comment]
@datitisev ok, I'll take a look at that and come up with a prototype.

**Comment by datitisev** [comment]
@CDK2020 We can probably do something like the following:
```js
const includesShortcode = (e, s) => e.shortcodes.includes(s);

// no skin
const emoji = <MAP>.find(e => includesShortcode(e, s));
const hexcode = emoji && emoji.hexcode;

// skin
const getSkin = (shortcode) => e => e.skins.find(skin => includesShortcode(skin, shortcode));
const emoji = <MAP>.find(e => e.skins.find(skin => includesShortcode(skin, s))).filter(Boolean);
const hexcode = emoji && getSkin(emoji).hexcode;
```

Haven't tested this.

**Pull request merged**
